### ISSUE TITLE
nameLocMap is missing definitions of some identifiers

### ISSUE THREAD

**Issue by michaelmesser** [idris-lang/Idris2#1506]
# Steps to Reproduce

```idris
test : Nat
test = let x = 1 in x
           ^        *
```

# Expected Behavior

The `x` with the `^` is in the `nameLocMap`.

# Observed Behavior

Only the `x` with the `*` us in `nameLocMap`.

```idris
Metadata:
 ...
 nameLocMap: fromList
   [ (("Test.idr", ((2, 0), (2, 4))), Test.test)
   , (("Test.idr", ((2, 7), (2, 10))), Prelude.Types.Nat)
   , (("Test.idr", ((3, 0), (3, 4))), Test.test)
   , (("Test.idr", ((3, 15), (3, 16))), Prelude.Num.fromInteger)
   , (("Test.idr", ((3, 20), (3, 21))), x)
   ]
 ...
```

**Comment by gallais** [comment]
Is there any useful information in `nameLocMap` that is not contained in the semantic
highlighting information? Because this should be present there.

**Comment by michaelmesser** [comment]
Yes. The semantic highlighting information does not have `fromString` for string literals.

**Comment by gallais** [comment]
A command to easily inspect the namelocmap would be convenient because here it's hard to
check what is or is not in there.

```
test : Nat
test = let x = "hi" in let x = 1 in x
--         ^        *
```

Checking with `typeAt` (`C-c C-t`) the type nof the first `x` in emacs I do get the correct `x : String` so
I'm tempted to thing that this may have been fixed?

**Comment by michaelmesser** [comment]
The command is `idris2 --ttm path/to/file.ttm`. I'm not entirely sure what the difference is between `names`, `nameLocMap`, and `semanticHighlighting` is supposed to be. Perhaps `names` and/or `nameLocMap` could be eliminated.

For:
```idris
test : Nat
test = let x = "hi" in let x = 1 in x
```
With `Idris 2, version 0.5.1-0bc18bd34` (November 19th), I get:
```idris
Metadata:
 lhsApps: []
 names:
     [ ((Test5, ((1, 11), (1, 12))), (x, (0, String)))
     , ((Test5, ((1, 27), (1, 28))), (x, (0, Prelude.Types.Nat)))
     , ((Test5, ((1, 36), (1, 37))), (x, (0, Prelude.Types.Nat)))
     , ((Test5, ((0, 0), (0, 4))), (Main.test, (0, Prelude.Types.Nat)))
     ]
 type declarations: [((Test5, ((0, 0), (0, 10))), (Main.test, (0, Prelude.Types.Nat)))]
 current LHS: Nothing
 holes: []
 nameLocMap: fromList
     [ ((Test5, ((0, 0), (0, 4))), Main.test)
     , ((Test5, ((0, 7), (0, 10))), Prelude.Types.Nat)
     , ((Test5, ((1, 0), (1, 4))), Main.test)
     , ((Test5, ((1, 36), (1, 37))), x)
     ]
 sourceIdent: Test5
 semanticHighlighting: fromList
     [ ((Test5, ((0, 0), (0, 4))), (function, Nothing))
     , ((Test5, ((0, 5), (0, 6))), (keyword, Nothing))
     , ((Test5, ((0, 7), (0, 10))), (type, Just Prelude.Types.Nat))
     , ((Test5, ((1, 0), (1, 4))), (function, Just Main.test))
     , ((Test5, ((1, 5), (1, 6))), (keyword, Nothing))
     , ((Test5, ((1, 7), (1, 10))), (keyword, Nothing))
     , ((Test5, ((1, 11), (1, 12))), (bound, Just x))
     , ((Test5, ((1, 13), (1, 14))), (keyword, Nothing))
     , ((Test5, ((1, 15), (1, 19))), (data, Nothing))
     , ((Test5, ((1, 20), (1, 22))), (keyword, Nothing))
     , ((Test5, ((1, 23), (1, 26))), (keyword, Nothing))
     , ((Test5, ((1, 27), (1, 28))), (bound, Just x))
     , ((Test5, ((1, 29), (1, 30))), (keyword, Nothing))
     , ((Test5, ((1, 31), (1, 32))), (data, Nothing))
     , ((Test5, ((1, 33), (1, 35))), (keyword, Nothing))
     , ((Test5, ((1, 36), (1, 37))), (bound, Just x))
     ]
 semanticAliases: fromList []
 semanticDefaults: fromList []
```
This is still missing the first two `x`s.
